### PR TITLE
lets try this again. This fixed the joystick problems included the bi…

### PR DESCRIPTION
**Pull request by ghost**
sorry about the other day had to read up a lot on github i didnt know what i was doing. This fixes the joystick input problems i do have the bin on my repo if you want to test it.

### CODE REVIEW

**Comment by joolswills** [comment]
Your PR has a bin file added - what's that ?

What's the control ini file ? is that required to be added to the repo ?

You have unrelated whitespace changes in the PR. I also need more details about the PR to accept it. thanks.

**Comment by ghost** [comment]
it to test the emu us the compiled bin

**Comment by ghost** [comment]
us - is

**Comment by joolswills** [comment]
We don't want precompiled binaries added to the repository.

**Comment by ghost** [comment]
ok so what do i do just remove it ?

**Comment by joolswills** [comment]
Please remove it, go over the other points I made. we can then review it. I have no idea what your changes achieve currently.

**Comment by ghost** [comment]
the joystick controls do not work in the emulator the way the are mapped thats why people have problems setting the joystick up because it was using the gp32 defaults when setting keyboard button as 0 which are in the compares

**Comment by joolswills** [comment]
when configuring controls in ES we create a daphe input configuration. When I tested it, it worked fine.

**Comment by ghost** [comment]
do i just make a new git commit to remove the bin ?

**Comment by joolswills** [comment]
yes, but no need to do it yet, as I'm not sure why this is needed still. We generate configs for daphe if it's installed and someone reconfigures their joystick on ES. Sorry but I need more detail as to what isn't working there.

**Comment by ghost** [comment]
ok i have removed the bin do i need to do another pull request or will you see it

**Comment by joolswills** [comment]
I can't see it if you haven't pushed it to github. But more importantly, I will not be able to accept this PR without you addressing the points I raised above.

**Comment by joolswills** [comment]
Another problem is that we don't use the master branch - we use the retropie branch. The master branch is not maintained here.

**Comment by ghost** [comment]
ok sorry about all this github stuff ill put a new pull req in

**Comment by joolswills** [comment]
Before you do, please give me some more detail as I will not accept a new PR without more information. You would do best to open an issue really and discuss there first.

**Pull request closed without merging**
